version: "3.5"

services:
    ngnix:
        build: build/nginx/
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./projects/:/var/www/
        networks:
            - web
            
    php-fpm:
        build:
            context: ./build/php-fpm
        container_name: php-fpm
        volumes:
            - ./projects/:/var/www/html/
        networks:
            - web

    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: dev
        volumes:
            - ./db/:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - web
    
networks:
    web:
        name: web