version: "3.5"

services:
    web:
        build: ./build/nginx/
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./projects/:/var/www/
        networks:
            - webdev
            
    php:
        build: ./build/php-fpm
        container_name: php-fpm
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./etc/php/php-fpm.d/www.conf:/usr/local/etc/php/php-fpm.d/www.conf
            - ./projects/:/var/www/
        networks:
            - webdev

    db:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./db/:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - webdev
    
networks:
    webdev:
        name: webdev