version: "3.5"

services:
    web:
        build: ./build/nginx/
        container_name: nginx
        ports:
            - "${PORT_NGINX}:80"
            - "${PORT_NGINX_SSL}:443"
        volumes:
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/auth:/etc/nginx/auth/
            - ./etc/letsencrypt/:/etc/letsencrypt/
            - ./projects/:/var/www/
        networks:
            - webdev
            
    php:
        build: ./build/php-fpm
        container_name: php-fpm
        ports:
            - "${PORT_PHP}:9000"
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini
            - ./projects/:/var/www/
        networks:
            - webdev

    db:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./db/:/var/lib/mysql
        ports:
            - "${PORT_MYSQL}:3306"
        networks:
            - webdev
    
networks:
    webdev:
        name: webdev