version: "3.5"

services:
    web:
        build: ./build/nginx/
        container_name: ${NGINX_CONTAINER_NAME}
        ports:
            - "${NGINX_PORT}:80"
            - "${NGINX_PORT_SSL}:443"
        volumes:
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/auth:/etc/nginx/auth/
            - ./etc/letsencrypt/:/etc/letsencrypt/
            - ./log/nginx:/var/log/nginx/
            - ${PROJECTS_DIR}:/var/www/
        networks:
            - webdev
            
    php:
        build: ./build/php-fpm
        container_name: ${PHP_CONTAINER_NAME}
        environment:
            XDEBUG_CONFIG: remote_host=${HOST_LOCAL_IP}
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini
            - ${PROJECTS_DIR}:/var/www/
        networks:
            - webdev

    db:
        image: mysql:5.7
        container_name: ${MYSQL_CONTAINER_NAME}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./db/:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - webdev
    
networks:
    webdev:
        name: ${NETWORK_NAME}